---

 - debug:
     msg: "_____INSTALL_MYSQL_____"

        #INSTALL_MYSQL DEB

 - name: install_mysql_deb
   apt:
     update_cache: yes
     state: latest
     pkg:
       - mariadb-client-10.3
       - mariadb-server-10.3
       - mariadb-server-core-10.3
   when:
     - ansible_distribution == "Debian"

        #INSTALL_MYSQL CENTOS

 - name: install_mysql_rh
   urpmi:
     update_cache: yes
     state: latest
     pkg:
       - mariadb
       - mariadb-server
   when:
     - ansible_distribution == "Mageia"

 - name: install_mysql_rh
   yum:
     update_cache: yes
     state: latest
     pkg:
       - mariadb
       - mariadb-server
       - MySQL-python
   when:
     - ansible_distribution == "CentOS" or ansible_distribution == "Rhel"

 - name: start mysqld Mageia
   service:
     name: mariadb
     state: started
   when:
     - ansible_distribution == "Mageia"

 - name: start mysqld rh
   systemd:
     name: mariadb
     state: started
   when:
     - ansible_distribution == "CentOS" or ansible_distribution == "Rhel"

 # - name: Change mysql root password and keep track in
 #   shell: |
 #     password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
 #     echo $password_match
 #     mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ ROOT_PASSWORD }}'; flush privileges; "
 #     echo "[client]"
 #     user=root
 #     password={{ ROOT_PASSWORD }} > /root/.my.cnf
 #   register: change_temp_pass
 #   notify: restart mysqld
 #   when:
 #     - ansible_distribution == "CentOS"

        #SECURE THE INSTALL
 - name: delete dire
   file:
     path: /var/lib/mysql
     state: absent

 - name: mysql_install_db
   shell: mysql_install_db

 - name: mysql_install_db
   shell: "chown -R mysql: /var/lib/mysql/"

 - name: restart mariadb
   service:
     name: mariadb
     state: restarted

 - name: enabled centos password
   shell: mysqladmin -u {{ DBADMINUSER }} password '{{ DBADMINPASSWD }}'
   when:
     - ansible_distribution == "CentOS"

 - name: settings for mysql-server UPDATE mysql.user SET Password=PASSWORD
   shell: echo "UPDATE mysql.user SET Password=PASSWORD('{{ DBADMINPASSWD }}') WHERE User='{{ DBADMINUSER }}'" | mysql -u root -p{{ DBADMINPASSWD }}

 - name: settings for mysql-server FLUSH PRIVILEGES
   shell: echo "FLUSH PRIVILEGES" | mysql -u {{ DBADMINUSER }} -p"{{ DBADMINPASSWD }}"

 - name: settings for mysql-server DELETE FROM mysql.user WHERE User='root' AND Host NOT IN
   shell: echo "DELETE FROM mysql.user WHERE User='{{ DBADMINUSER }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')" | mysql -u {{ DBADMINUSER }} -p"{{ DBADMINPASSWD }}"

 - name: settings for mysql-server DELETE FROM mysql.user WHERE User=''"
   shell: echo "DELETE FROM mysql.user WHERE User=''" | mysql -u {{ DBADMINUSER }} -p"{{ DBADMINPASSWD }}"

 - name: settings for mysql-server DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
   shell: echo "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'" | mysql -u {{ DBADMINUSER }} -p"{{ DBADMINPASSWD }}"

 - name: settings for mysql-server FLUSH PRIVILEGES
   shell: echo "FLUSH PRIVILEGES" | mysql -u {{ DBADMINUSER }} -p"{{ DBADMINPASSWD }}"
