PKI_PATH: /var/lib/pulse2/pki
PKI_SERVER: localhost
SERVER_FQDN: '{{ ansible_fqdn }}'
XMPP_DOMAIN: pulse
XMPP_MASTER_PASSWORD: '' # 12 character string. Must be vaulted
LDAP_BASEDN: 'dc={{ ansible_domain.split(".") | join(",dc=")}}'
LDAPADMINPASSWD: '{{ ROOT_PASSWORD }}'
# For authenticating to external LDAP. Examples:
# EXTERNAL_LDAP_URL: ldap://ldap.siveo.local:389 
# EXTERNAL_LDAP_SUFFIX: OU=USERS,OU=AD,DC=siveo,DC=local
# EXTERNAL_LDAP_BINDNAME: CN=readonly,OU=SERVICE_ACCOUNTS,OU=AD,DC=siveo,DC=local
EXTERNAL_LDAP_URL: ''
EXTERNAL_LDAP_SUFFIX: ''
EXTERNAL_LDAP_BINDNAME: ''
EXTERNAL_LDAP_PASSWORD: ''
EXTERNAL_LDAP_USERATTR: sAMAccountName
INTERFACE: '{{ ansible_default_ipv4.interface }}'
IP_ADDRESS: "{{ vars['ansible_'~INTERFACE].ipv4.address }}"
# Define PUBLIC_IP if main pulse server also has a public relay. TODO: Maybe this needs to go in another task
PUBLIC_IP: ''
GUACAMOLE_ROOT_PASSWORD: '' # GUACAMOLE_ROOT_PASSWORD comes from guacamole role
AES_KEY: '' # 32 character string. Must be vaulted
GRAFANA_ADMIN_KEY: '' # GRAFANA_ADMIN_KEY is generated by grafana role
STDISCOSRV_URL: '' # STDISCOSRV_URL is generated by syncthing_discosrv role
# For using database on another server, define DBHOST
DBHOST: localhost
DBPORT: 3306
DBUSER: mmc
DBPASSWORD: '' # 12 character string. Must be vaulted
DBADMINUSER: root
DBADMINPASSWD: '{{ ROOT_PASSWORD }}'
# For using glpi on another server, redefine following GLPI_* variables. The following defaults are for local glpi.
GLPI_DBHOST: localhost
GLPI_DBPORT: 3306
GLPI_DBNAME: glpi
GLPI_DBUSER: glpi
GLPI_DBPASSWD: '' # 12 character string. Must be vaulted
GLPI_BASEURL: 'http://{{ SERVER_FQDN }}/glpi'
ITSM_API_USER: 'root'
ITSM_API_PASSWORD: '{{ ITSM_ADMINPASSWD }}'
URBACKUP_API_SERVER: 127.0.0.1
URBACKUP_ADMINPASSWD: '{{ ROOT_PASSWORD }}'
URBACKUP_API_PASSWORD: '' # URBACKUP_API_PASSWORD comes from urbackup role
PYTHON_VERSION: 3
