---

# Create the multisite entity in GLPI. Done on main pulse server

 - name: set MAX_ID
   set_fact:
     MAX_ID: ssh {{ GLPI_DBHOST }} "echo 'SELECT MAX(id) FROM glpi_entities;' | mysql -s glpi"

 - name: shell MAX_ID
   shell: '{{ MAX_ID }}'
   register: outMAX_ID

 - name: set MAX_ID
   set_fact:
     MAX_ID: '{{ outMAX_ID.stdout }}'

 - name: set ID
   set_fact:
     ID: ({{ MAX_ID }}+1)

 - name: shell id
   shell: '{{ ID }}'
   register: idOut

 - name: set ID
   set_fact:
     ID: '{{ idOut.stdout }}'

 - name: set GLPI_MAIN_ENTITY
   set_fact:
     GLPI_MAIN_ENTITY: echo 'SELECT completename FROM glpi_entities WHERE id='0';' | mysql -s glpi

 - name: shell GLPI_MAIN_ENTITY
   shell: '{{ GLPI_MAIN_ENTITY }}'
   register: outGlpi

 - name: set GLPI_MAIN_ENTITY
   set_fact:
     GLPI_MAIN_ENTITY: '{{ outGlpi.stdout }}'

 - name: set SSH_COMMAND
   set_fact:
     SSH_COMMAND: echo "INSERT INTO glpi_entities (id,entities_id,level,name,completename) VALUES ('{{ ID }}','0','2','{{ MULTISITE_ENTITY }}','{{ GLPI_MAIN_ENTITY }} > {{ MULTISITE_ENTITY }}');" | mysql glpi

 - name: shell
   shell: ssh {{ GLPI_DBHOST }} {{ SSH_COMMAND }}

### Create fusioninventory rule to affect all computer from/to multi-site entity. Done on main pulse server

 - name: set SSH_COMMAND_UPDATE_RANKING
   set_fact:
     SSH_COMMAND_UPDATE_RANKING: echo "UPDATE glpi_rules SET ranking = ranking+1 WHERE sub_type = 'PluginFusioninventoryInventoryRuleEntity';" | mysql glpi

 - name: set SSH_COMMAND_GLPI_RULES
   set_fact:
     SSH_COMMAND_GLPI_RULES: echo "INSERT INTO glpi_rules VALUES ('','','PluginFusioninventoryInventoryRuleEntity',1,'{{ MULTISITE_ENTITY }}','','AND',1,'','',0,'',0,'');" | mysql glpi

 - name: set SSH_COMMAND_GLPI_RULECRITERIAS
   set_fact:
     SSH_COMMAND_GLPI_RULECRITERIAS: echo "INSERT INTO glpi_rulecriterias VALUES ('', (SELECT MAX(id) FROM glpi_rules WHERE sub_type = 'PluginFusioninventoryInventoryRuleEntity' ),'subnet',0,'{{ NETWORK_ADDRESS }}');" | mysql glpi

 - name: set SSH_COMMAND_GLPI_RULEACTIONS
   set_fact:
     SSH_COMMAND_GLPI_RULEACTIONS: echo "INSERT INTO glpi_ruleactions VALUES ('', (SELECT MAX(id) FROM glpi_rules WHERE sub_type = 'PluginFusioninventoryInventoryRuleEntity' ),'assign','entities_id',(SELECT id FROM glpi_entities WHERE name='{{ MULTISITE_ENTITY }}'));" | mysql glpi

#    ssh ${GLPI_DBHOST} ${SSH_COMMAND_UPDATE_RANKING}
#    ssh ${GLPI_DBHOST} ${SSH_COMMAND_GLPI_RULES}
#    ssh ${GLPI_DBHOST} ${SSH_COMMAND_GLPI_RULECRITERIAS}
#    ssh ${GLPI_DBHOST} ${SSH_COMMAND_GLPI_RULEACTIONS}

 - name: shell ssh command
   shell: ssh {{ GLPI_DBHOST }} {{ SSH_COMMAND_UPDATE_RANKING }}

 - name: shell ssh command
   shell: ssh {{ GLPI_DBHOST }} {{ SSH_COMMAND_GLPI_RULES }}

 - name: shell ssh command
   shell: ssh {{ GLPI_DBHOST }} {{ SSH_COMMAND_GLPI_RULECRITERIAS }}

 - name: shell ssh command
   shell: ssh {{ GLPI_DBHOST }} {{ SSH_COMMAND_GLPI_RULEACTIONS }}
