---

 - name: shell
   shell: echo "select 0;" | mysql -h{{ GLPI_DBHOST }} -P{{ GLPI_DBPORT }} -u{{ GLPI_DBUSER }} -p{{ GLPI_DBPASSWD }} {{ GLPI_DBNAME }} &> /dev/null
   ignore_erros: yes
   register: resmysqlco
   when:
     - GLPI_DBHOST != PULSEMAIN_IP

 - name: msg
   debug:
     msg: 'Remote mysql connection to GLPI database succeeded'
   when:
     - resmysqlco == 0
     - GLPI_DBHOST != PULSEMAIN_IP

 - name: msg
   debug:
     msg: 'Error connecting to GLPI database {{ GLPI_DBNAME }} at {{ GLPI_DBHOST }}'
   when:
     - resmysqlco != 0
     - GLPI_DBHOST != PULSEMAIN_IP
