---

 # - name: Get hostname
 #   shell: hostname -f
 #   register: result
 #
 # - name: set xmppDomain = 1
 #   set_fact:
 #     XMPP_DOMAIN: "{{ result.stdout }}"
 #
 # - name: shell sed
 #   shell: sed "s/^bind-address.*/bind-address             = 0.0.0.0/g" -i /etc/mysql/mariadb.conf.d/50-server.cnf
 #   when:
 #     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"
 #     - GLPI_DBHOST == PULSEMAIN_IP
 #
 # - name: shell sed
 #   shell: sed "s/^bind-address.*/bind-address             = 0.0.0.0/g" -i /etc/my.cnf
 #   when:
 #     - ansible_distribution == "CentOS" or ansible_distribution == "Rhel"
 #     - GLPI_DBHOST == PULSEMAIN_IP
 #
 #     # Create remote glpi user
 #
 # - name: shell mysql command
 #   shell: echo "GRANT ALL PRIVILEGES ON {{ GLPI_DBNAME }}.* to '{{ GLPI_DBUSER }}'@'{{ IP_REMOTE_SERVER1 }}' identified by '{{ ROOT_PASSWORD }}';" |mysql -s
 #   when:
 #     - GLPI_DBHOST == PULSEMAIN_IP
 #
 # - name: shell mysql command
 #   shell: echo "GRANT ALL PRIVILEGES ON {{ GLPI_DBNAME }}.* to '{{ GLPI_DBUSER }}'@'{{ IP_REMOTE_SERVER2 }}' identified by '{{ ROOT_PASSWORD }}';" |mysql -s
 #   when:
 #     - GLPI_DBHOST == PULSEMAIN_IP
 #
 # - name: restarted mariadb
 #   systemd:
 #     name: mariadb
 #     state: restarted
 #   when:
 #     - GLPI_DBHOST == PULSEMAIN_IP

###ELSE GLPI_DBHOST != PULSEMAIN_IP

 - name: shell
   shell: echo "select 0;" | mysql -h{{ GLPI_DBHOST }} -P{{ GLPI_DBPORT }} -u{{ GLPI_DBUSER }} -p{{ GLPI_DBPASSWD }} {{ GLPI_DBNAME }} &> /dev/null
   ignore_errors: yes
   register: resmysqlco
   when:
     - GLPI_DBHOST != PULSEMAIN_IP

 - name: msg
   debug:
     msg: 'Remote mysql connection to GLPI database succeeded'
   when:
     - resmysqlco == 0
     - GLPI_DBHOST != PULSEMAIN_IP

 - name: msg
   debug:
     msg: 'Error connecting to GLPI database {{ GLPI_DBNAME }} at {{ GLPI_DBHOST }}'
   when:
     - resmysqlco != 0
     - GLPI_DBHOST != PULSEMAIN_IP
