- name: ITSM-NG - Delete database user
  community.mysql.mysql_user:
    login_host: '{{ ITSM_DBHOST }}'
    login_port: '{{ ITSM_DBPORT }}'
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    name: '{{ ITSM_DBUSER }}'
    host_all: yes
    state: absent

- name: ITSM-NG - Delete database
  community.mysql.mysql_db:
    login_host: '{{ ITSM_DBHOST }}'
    login_port: '{{ ITSM_DBPORT }}'
    login_user: '{{ DBADMINUSER }}'
    login_password: '{{ DBADMINPASSWD }}'
    name: '{{ ITSM_DBNAME }}'
    state: absent

- name: ITSM-NG - Delete previous config file
  ansible.builtin.file:
    path: /etc/itsm-ng/config/config_db.php
    state: absent
    
- name: ITSM-NG - Delete marker set for database initialisation
  ansible.builtin.file:
    path: /var/lib/itsm-ng/.dbinitialised
    state: absent

