---

 - name: install_multisite_dependencies
   hosts: relay
   remote_user: root
   vars:
     - PULSE4REPO_URL: 'https://cnam.siveo.net/pulse4.repo'
     - ROOT_PASSWORD: 'siveo'
     - DBHOST: 'localhost'
     - DBPORT: '3306'
     - DBADMINUSER: 'root'
     - DBADMINPASSWD: 'siveo'
     - REVERSE_SSH_PORT: ''
     - PUBLIC_IP: '212.83.163.33'
     - CLIENTS_SSH_PORT: ''
     - CLIENTS_VNC_PORT: ''
     - PULSEMAIN_IP: '10.62.19.40'
     - PULSEMAIN_FQDN: 'wva-mmc.siveo.lan'
     - PKI_PASSWORD: 'siveo'
     - GLPI_DBHOST: 'localhost'
     - GLPI_DBPORT: '3306'
     - GLPI_DBUSER: 'root'
     - GLPI_DBPASSWD: 'siveo'
     - GLPI_DBNAME: 'glpi'
     - SERVER_FQDN: 'wva-ars1.siveo.lan'
     - INSTALL_TYPE: 'm'
     - INTERFACE_TO_PULSE: 'ens192'
     - INTERFACE: 'ens192'
     - MULTISITE_ENTITY: ''                                                                                                                                   │····················································
     - MAIN_ENTITY: ''

   roles:
     - pulse4ambx
