---
- name: install pulse
  hosts: all
  remote_user: root
  serial: 1
  roles:
    - pulse4ambx
  when: 
    - (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or (ansible_distribution == 'Debian')
