---

 - name: install_multisite_dependencies
   hosts: relay
   remote_user: root
   vars:
     - PULSE4REPO_URL: 'https://cnam.siveo.net/pulse4.repo'
     - ROOT_PASSWORD: 'siveo'
     - DRIVERS_PASSWORD: 's3cr3t'
     - DBHOST: 'localhost'
     - DBPORT: '3306'
     - DBADMINUSER: 'root'
     - DBADMINPASSWD: 'siveo'
     - REVERSE_SSH_PORT: ''
     - PUBLIC_IP: '212.83.163.33'
     - CLIENTS_SSH_PORT: ''
     - CLIENTS_VNC_PORT: ''
     - MULTISITE_ENTITY: 'Main'
     - PULSEMAIN_IP: '10.62.19.40'
     - PULSEMAIN_FQDN: 'wva-mmc.siveo.lan'
     - PKI_PASSWORD: 'siveo'
     - GLPI_DBHOST: 'localhost'
     - GLPI_DBPORT: '3306'
     - GLPI_DBUSER: 'root'
     - GLPI_DBPASSWD: 'siveo'
     - GLPI_DBNAME: 'glpi'
     - CREATE_ENTITY: 'y'
     - SERVER_FQDN: 'wva-ars1.siveo.lan'
     - INSTALL_TYPE: 'm'
     - INTERFACE_TO_PULSE: 'ens192'
     - INTERFACE: 'ens192'
     - XMPP_DOMAIN: ''
     - key: /root/.ssh/id_rsa.pub
     - v_php: php7.0
     - V_PHP_TEST_DEB: ''
     - V_PHP_TEST_CENT: ''
     - TOMCAT_VERSION_MAG: '6'
     - V_TOMCAT_TEST_DEB: ''
     - V_TOMCAT_TEST_CENT: ''
     - RELAY_CONFIG_FILE: ''
     - PLUGINLIST: ''
     - SSH_COMMAND: ''
     - MASTER_PASSWORD: ''
     - GUACAMOLE_BASEURL: ''
     - IP_REMOTE_SERVER: ''
     - IP_ADDRESS: ''
     - PLUGIN_CONFIG_FILE: ''
     - MAX_ID: ''
     - CLUSTER_ID: ''
     - RELAYSERVER_ID: ''
     - SYSLINUX_PATH: ''
     - PXELINUX_PATH: ''
     - TOMCAT_VERSION: ''
     - HOSTNAME_F: ''
     - REVERSESSH: ''
     - GATEWAYPORTS_RES: ''
     - SYNCTHING_APACHE_PATH: ''
     - GUACAMOLE_ROOT_PASSWORD: ''
     - GUACAMOLE_APACHE_PATH: ''
     - PULSEMAIN_DEVICE_ID: ''
     - LOCAL_DEVICE_ID: ''
     - SHARE_ADDED: ''
     - ENABLE_CHANGE_PASS_CENT: 'true'
     - SSL_CONF_FILE: ''
     - PACKAGESERVER_UUID: ''
     - NETMASK: '255.255.255.0'
     - UUID: ''
     - UUID_IMAGING: ''
     - GLPI_ENTITY_ID: ''

   roles:
     - pulse4ambx
