---

 - name: install_multisite_dependencies
   hosts: relay
   remote_user: root
   vars:
     - PULSE_REPO_URL: "https://git.siveo.net"
     - PULSE_REPO_RPM_URL: "https://git.siveo.net"
     - GIT_BRANCH: "integration"
     - XMPP_DOMAIN: "siveo"
     - key: /root/.ssh/id_rsa.pub
     - v_php: php7.0
     - V_PHP_TEST_DEB: ''
     - V_PHP_TEST_CENT: ''
     - TOMCAT_VERSION_MAG: "6"
     - V_TOMCAT_TEST_DEB: ''
     - V_TOMCAT_TEST_CENT: ''
     - ROOT_PASSWORD: r00tSiveo*
     - DRIVERS_PASSWORD: ''
     - TEMP_PASS_MYSQL: siveo
     - SERVER: "pulse"
     - mysql_user: root
     - RELAY_CONFIG_FILE: '/etc/pulse-xmpp-agent/relayconf.ini'
     - PLUGINLIST: ''
     - SSH_COMMAND: ''
     - MASTER_PASSWORD: 'root'
     - GUACAMOLE_BASEURL: ''
     - IP_REMOTE_SERVER: ''
     - REVERSE_SSH_PORT: ''
     - IP_ADDRESS: ''
     - PUBLIC_IP: ''
     - PLUGIN_CONFIG_FILE: ''
     - CLIENTS_SSH_PORT: ''
     - CLIENTS_VNC_PORT: ''
     - MAX_ID: ''
     - CLUSTER_ID: ''
     - MULTISITE_ENTITY: ''
     - PULSEMAIN_IP: 'wva-mmc.siveo.lan'
     - RELAYSERVER_ID: ''
     - PULSEMAIN_FQDN: 'wva-mmc.siveo.lan'
     - SYSLINUX_PATH: ''
     - PXELINUX_PATH: ''
     - TOMCAT_VERSION: ''
     - HOSTNAME_F: ''
     - REVERSE_SSH_PORT: ''
     - REVERSESSH: ''
     - GATEWAYPORTS_RES: ''
     - SYNCTHING_APACHE_PATH: ''
     - GUACAMOLE_ROOT_PASSWORD:
     - SERVER_FQDN: ''
     - INSTALL_TYPE: ''
     - GUACAMOLE_APACHE_PATH: ''
     - PULSEMAIN_DEVICE_ID: ''
     - LOCAL_DEVICE_ID: ''
     - SHARE_ADDED: ''

   roles:

#INSTALL_MULTSITE_DEPENDENCIES
     - config_repo_pulse
     - config_start
#INSTALL_MULTSITE
     - install_/multisite
#INSTALL_MULTSITE_DEPENDENCIES
     - install_/apache2_php
     - install_/php
     - install_/mysql
     - install_/nfs_kernel
     - config_/nfc_kernel
     - install_/pxelinux
     - config_/pxelinux
     - install_/clonezilla
     - config_/clonezilla
     - install_/samba
     - config_/samba
     - install_/xmpp
     - config_/xmpp
     - install_/guacamole
     - config_/guacamole
     - install_/syncthing
     - config_/syncthing
     - config_/syncthing_depl
     - config_/mysql_access
     - config_/mysql_server
     - config_/ssh_server
     - config_relay_server

 - name: config_guacamole_pulse_task
   hosts: pulse
   remote_user: root
   vars:
     - GUACAMOLE_APACHE_PATH: ''
     - SERVER_FQDN: 'wva-mmc.siveo.lan'
     - PULSEMAIN_FQDN: 'wva-mmc.siveo.lan'
     - SHARE_ADDED: ''
     - LOCAL_DEVICE_ID: ''

   roles:
     - config_/guacamole_pulse
