---

 - name: install_relay
   hosts: wva_servers
   remote_user: root
   vars:
     - PULSE4REPO_URL: 'https://git.siveo.net/integration.list'
     - ROOT_PASSWORD: 'siveo'
     - DBHOST: 'localhost'
     - DBPORT: '3306'
     - DBADMINUSER: 'root'
     - DBADMINPASSWD: 'siveo'
     - REVERSE_SSH_PORT: ''
     - PUBLIC_IP: '212.83.163.33'
     - CLIENTS_SSH_PORT: ''
     - CLIENTS_VNC_PORT: ''
     - PULSEMAIN_IP: '10.62.19.40'
     - PULSEMAIN_FQDN: 'wva-mmc.siveo.lan'
     - PKI_PASSWORD: 'siveo'
     - GLPI_DBHOST: 'localhost'
     - GLPI_DBPORT: '3306'
     - GLPI_DBUSER: 'root'
     - GLPI_DBPASSWD: 'siveo'
     - GLPI_DBNAME: 'glpi'
     - DRIVERS_PASSWORD: s3cr3t
     - SERVER_FQDN: 'wva-ars1.siveo.lan'
     - INSTALL_TYPE: 'm'
     - INTERFACE_TO_PULSE: 'ens192'
     - INTERFACE: 'ens192'
     - MULTISITE_ENTITY: ''
     - MAIN_ENTITY: ''
     - PULSE4REPOKEY_URL: 'https://git.siveo.net/pubkey.txt'
     - DEB_PHP_VERSION: '7.0'
     - SHARE:
         share_id:
           share_id_name: 'pulsemaster_packages'
         share_id:
           share_id_name: 'pulsemaster_downloads'
         share_id:
           share_id_name: 'pulsemaster_bootmenus'
         share_id:
           share_id_name: 'pulsemaster_baseremoteagent'
         syncthing_folder:
           syncthing_folder_name: 'packages'
         syncthing_folder:
           syncthing_folder_name: 'downloads'
         syncthing_folder:
           syncthing_folder_name: 'bootmenus'
         syncthing_folder:
           syncthing_folder_name: 'baseremoteagent'
         destination:
           destination_name: '/telediffusion/4/'
         destination:
           destination_name: '/var/lib/pulse2/clients/'
         destination:
           destination_name: '/var/lib/pulse2/imaging/bootmenus/'
         destination:
           destination_name: '/var/lib/pulse2/xmpp_baseremoteagent/'
   roles:
     - pulse4ambx
