SERVER_FQDN: '{{ ansible_fqdn }}'
DRIVERS_PASSWORD: '' # 12 character string. Must be vaulted
DRIVERS_FOLDER: /var/lib/pulse2/imaging/postinst/sysprep/drivers
ITSM_TYPE: glpi # can be itsm-ng
ITSM_DBHOST: localhost
ITSM_DBPORT: 3306
ITSM_DBUSER: glpi
ITSM_DBPASSWD: '' # 12 character string. Must be vaulted
ITSM_DBNAME: glpi
ENTITY: Public
CLUSTER_NAME: '{{ ENTITY }}'
ORGANISATION: Siveo Pulse
IMAGING_SERVER_NAME: '{{ ENTITY }}'
NETWORK_ADDRESS: "{{ vars['ansible_'~INTERFACE].ipv4.network }}"
CLIENTS_SSH_PORT: 22
CLIENTS_VNC_PORT: 5900
DBHOST: localhost
DBPORT: 3306
DBUSER: mmc
DBPASSWORD: '' # 12 character string. Must be vaulted
URBACKUP_SERVERADDRESS: '{{ ansible_fqdn }}'
URBACKUP_SERVERPORT: 55415
