---

 - name: Get hostname
   shell: hostname -s
   register: result

 - name: set xmppDomain = 1
   set_fact:
     XMPP_DOMAIN: "{{ result.stdout }}"

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: '{{ LOCAL_DEVICE_ID }}'
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: delete file if present
   file:
     path: /var/lib/syncthing/packages
     state: absent

 - name: create file
   file:
     path: /var/lib/syncthing/packages
     state: directory
     mode: '0755'

 - name: install acl
   apt:
     update_cache: yes
     state: latest
     pkg:
       - acl
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: shell
   shell: setfacl -Rdm g:syncthing:rwx /var/lib/pulse2/packages/

 - name: shell
   shell: setfacl -Rm g:syncthing:rwx /var/lib/pulse2/packages/

 - name: stman
   shell: stman folder add --label packages --foldertype readonly /var/lib/pulse2/packages/ pulsemaster_packages
   when:
     - XMPP_DOMAIN == 'pulse'

 - name: restarted syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: stopped
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: Check if d folder is empty before proceeding
   find:
     paths: '/var/lib/syncthing/packages/'
   register: filesFound

 - name: Move foo to bar
   command: mv /var/lib/syncthing/packages/.st*  /var/lib/pulse2/packages/
   when:
     - XMPP_DOMAIN != 'pulse'
     - filesFound.matched > 0

 - name: delete file if present
   file:
     path: /var/lib/syncthing/packages
     state: absent
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: shell
   shell: xmlstarlet ed --inplace -u "configuration/folder[@id='pulsemaster_packages']/@path" -v "/var/lib/pulse2/packages" /var/lib/syncthing/.config/syncthing/config.xml
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: restarted syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: restarted
   when:
     - XMPP_DOMAIN != 'pulse'

 - pause:
     seconds: 5
   when:
     - XMPP_DOMAIN != 'pulse'
