---

##_configure_package_server_multisite

 # - name: set PACKAGESERVER_UUID
 #   set_fact:
 #     PACKAGESERVER_UUID: "uuidgen"
 #
 #   # Enable the Pulse MMC to listen from everywhere. Done on main Pulse server
 # - name: shell crudini
 #   shell: crudini --set /etc/mmc/agent/config.ini.local main host 0.0.0.0 && systemctl restart mmc-agent.service
 #
 #   # Insert multisite imaging server in Pulse imaging server database. Done on main Pulse server.
 # - name: shell mysql command
 #   shell: echo "INSERT INTO ImagingServer (name, url, fk_default_menu, packageserver_uuid, \'recursive\', associated, fk_language, fk_entity) VALUES ('{{ MULTISITE_ENTITY }}', 'https://{{ IP_REMOTE_SERVER1 }}:9990/imaging_api', 1, '{{ PACKAGESERVER_UUID }}', 1, 0, 1, 1);" | mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} imaging
 #
 # - name: shell mysql command
 #   shell: echo "INSERT INTO ImagingServer (name, url, fk_default_menu, packageserver_uuid, \'recursive\', associated, fk_language, fk_entity) VALUES ('{{ MULTISITE_ENTITY }}', 'https://{{ IP_REMOTE_SERVER2 }}:9990/imaging_api', 1, '{{ PACKAGESERVER_UUID }}', 1, 0, 1, 1);" | mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} imaging
 #
 #   # Create multisite imaging entity in Pulse imaging entities database. Done on main Pulse server
 # - name: shell mysql command
 #   shell: echo 'SELECT id FROM imaging.ImagingServer ORDER BY id DESC LIMIT 1'|mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} -s
 #   register: uuidimag
 #
 # - name: set UUID_IMAGING
 #   set_fact:
 #     UUID_IMAGING: UUID'{{ uuidimag.stdout }}'
 #
 # - name: shell mysql command
 #   shell: echo "SELECT id FROM {{ GLPI_DBNAME }}.glpi_entities WHERE name='{{ MULTISITE_ENTITY }}';" |mysql -h{{ GLPI_DBHOST}} -P {{ GLPI_DBPORT }} -u{{ GLPI_DBUSER }} -p{{ GLPI_DBPASSWD }} -s
 #   register: glpientity
 #
 # - name: set GLPI_ENTITY_ID
 #   set_fact:
 #     GLPI_ENTITY_ID: '{{ glpientity.stdout }}'
 #
 # - name: set UUID
 #   set_fact:
 #     UUID: UUID'{{ GLPI_ENTITY_ID }}'
 #
 # - name: shell mysql command
 #   shell: echo "INSERT INTO imaging.Entity (name, uuid, pxe_keymap) values ('{{ MULTISITE_ENTITY }}','{{ UUID }}','fr_FR');" | mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} imaging
 #
 #   # Register multisite package server in Pulse. Done on main Pulse server
 # - name: shell mysql command
 #   shell: echo 'SELECT id FROM imaging.Entity  ORDER BY id DESC LIMIT 1'|mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} -s
 #   register: idout
 #
 # - name: set ID
 #   set_fact:
 #     ID: '{{ idout.stdout }}'
 #
 # - name: shell mysql command
 #   shell: echo "UPDATE ImagingServer SET associated=1, fk_entity={{ ID }} WHERE packageserver_uuid='{{ PACKAGESERVER_UUID }}';"| mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }} imaging
 #
 # - name: ssh restart pulse2-package-server
 #   shell: ssh {{ IP_REMOTE_SERVER1 }} systemctl restart pulse2-package-server
 #
 # - name: ssh restart pulse2-package-server
 #   shell: ssh {{ IP_REMOTE_SERVER2 }} systemctl restart pulse2-package-server
