---

 - debug:
     msg: "_____CONFIG_&_DOWNLOAD_____"

 - name: fetch id_rsa.pub from pulemain
   fetch:
     src: '/.ssh/id_rsa.pub'
     dest: '/tmp/pulsemain-id_rsa.pub'
     flat: yes
   delegate_to: '{{ PULSEMAIN_IP }}'

 - name: set authorized key
   authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', '/tmp/pulsemain-id_rsa.pub') }}"

 - name: fetch id_rsa.pub from ambox
   fetch:
     src: '/.ssh/id_rsa.pub'
     dest: '/tmp/{{ansible_hostname}}-id_rsa.pub'
     flat: yes

 - name: set authorized_key
   authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', '/tmp/{{ansible_hostname}}-id_rsa.pub') }}"
   delegate_to: '{{ PULSEMAIN_IP }}'


#get ip

 - name: Get IP_ADDRESS
   shell: ip addr show {{ INTERFACE }} | grep -w inet | awk '{print $2}' | cut -d "/" -f 1
   register: resultip

 - name: set IP_ADDRESS
   set_fact:
     IP_ADDRESS: "{{ resultip.stdout }}"

#get ip

 - name: Get IP_REMOTE_SERVER
   shell: ip addr show {{ INTERFACE_TO_PULSE }} | grep -w inet | awk '{print $2}' | cut -d "/" -f 1
   register: ipadressout

 - name: set IP_REMOTE_SERVER
   set_fact:
     IP_REMOTE_SERVER: '{{ ipadressout.stdout }}'

#

#CONFIGURE ejabberd

 - name: install_ejabberd_rh
   yum:
     name: "{{ packages_cent }}"
     update_cache: yes
     state: latest
   vars:
     packages_cent:
       - ejabberd
   when:
     - ansible_distribution == "CentOS" or ansible_distribution == "CentOS"

 - name: install_ejabberd_deb
   apt:
     update_cache: yes
     state: latest
     pkg:
       - ejabberd
   when:
     - ansible_distribution == "Debian"

 - name: install_ejabberd_mag
   urpmi:
     update_cache: yes
     state: latest
     pkg:
       - ejabberd
   when:
     - ansible_distribution == "Mageia"

#---------

 - name: install crudini
   apt:
     update_cache: yes
     state: latest
     pkg:
       - crudini
   when:
     - ansible_distribution == "Debian"

 - name: install_crudini
   urpmi:
     update_cache: yes
     state: latest
     pkg:
       - crudini
   when:
     - ansible_distribution == "Mageia"

 - name: install_crudini
   yum:
     update_cache: yes
     state: latest
     pkg:
       - crudini
   when:
     - ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
