- name: GUACAMOLE - Restart guacd
  ansible.builtin.systemd:
    name: guacd
    state: restarted
    daemon_reload: yes

- name: GUACAMOLE - Restart tomcat
  ansible.builtin.systemd:
    name: '{{ TOMCAT_DAEMON }}'
    state: restarted
    daemon_reload: yes
