---

 - name: Get hostname
   shell: hostname -s
   register: result

 - name: set xmppDomain = 1
   set_fact:
     XMPP_DOMAIN: "{{ result.stdout }}"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_ROOT_PASSWORD: 'pwgen --secure 40 1'

 - stat:
     path: /etc/guacamole/guacamole.properties.bak
   register: stfile

 - name: shell
   shell: "/bin/cp /etc/guacamole/guacamole.properties /etc/guacamole/guacamole.properties.bak"
   when: stfile.stat.isreg is not defined

 - name: DROP DATABASE
   shell: 'echo "DROP DATABASE IF EXISTS guacamole;" | mysql -uroot'

 - name: DROP USER
   shell: echo "DROP USER IF EXISTS 'guacamole'@'localhost';" | mysql -uroot
   when: ansible_distribution == "Debian"

 - name: DROP USER
   shell: echo "DROP USER 'guacamole'@'localhost';" | mysql -uroot
   when: ansible_distribution != "Debian"

 - name: CREATE DATABASE
   shell: echo "CREATE DATABASE guacamole;" | mysql -uroot

 - name: CREATE USER
   shell: echo "CREATE USER 'guacamole'@'localhost' IDENTIFIED BY '{{ ROOT_PASSWORD }}';" | mysql -uroot

 - name: GRANT
   shell: echo "GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole.* TO 'guacamole'@'localhost';" | mysql -uroot

# if debian version 8

 - name: DROP USER
   shell: "mysql -uroot guacamole < /usr/share/guacamole-auth-mysql/schema/001-create-schema.sql;"
   when: ansible_distribution_major_version == '8'

 - name: DROP USER
   shell: "mysql -uroot guacamole < /usr/share/guacamole-auth-mysql/schema/002-create-admin-user.sql;"
   when: ansible_distribution_major_version == '8'

 - name: DROP USER
   shell: "mysql -uroot guacamole < /usr/share/guacamole-auth-jdbc/mysql/schema/001-create-schema.sql;"
   when: ansible_distribution_major_version != '8'

 - name: DROP USER
   shell: "mysql -uroot guacamole < /usr/share/guacamole-auth-jdbc/mysql/schema/002-create-admin-user.sql;"
   when: ansible_distribution_major_version != '8'

#

 - name: SET
   shell: echo "SET @salt = UNHEX(SHA2(UUID(), 256)); UPDATE guacamole_user SET username='root', password_salt=@salt, password_hash=UNHEX(SHA2(CONCAT('{{ GUACAMOLE_ROOT_PASSWORD }}', HEX(@salt)), 256)) WHERE user_id=1;" | mysql -uroot guacamole

#

 - stat:
     path: /etc/guacamole/guacamole.properties.bak
   register: stfiletwo

 - name: shell
   shell: "/bin/cp /etc/guacamole/guacamole.properties.bak /etc/guacamole/guacamole.properties"
   when: stfiletwo.stat.isreg is defined

 - stat:
     path: /etc/guacamole/lib
   register: std

 - name: creat directory /guacamole/lib
   file:
     path: /etc/guacamole/lib
     state: directory
   when:
     - stfiletwo.stat.isdir is defined
     - ansible_distribution == "Rhel" or ansible_distribution == "CentOS"

 - name: shell
   shell: "/bin/cp -f /usr/share/java/mysql-connector-java.jar /etc/guacamole/lib/"
   when:
     - stfiletwo.stat.isdir is defined
     - ansible_distribution == "Rhel" or ansible_distribution == "CentOS"

 - name: shell
   shell: 'sed -i "s/^auth-provider:.*$/auth-provider: net.sourceforge.guacamole.net.auth.mysql.MySQLAuthenticationProvider/" /etc/guacamole/guacamole.properties'
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

#wirte in file guacamole.properties

 - name: write in file
   copy:
     content: "# Hostname and port of guacamole proxy"
     dest: /etc/guacamole/guacamole.properties
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

 - name: write in file
   copy:
     content: "guacd-hostname: localhost"
     dest: /etc/guacamole/guacamole.properties
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

 - name: write in file
   copy:
     content: "guacd-port:     4822"
     dest: /etc/guacamole/guacamole.properties
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

 - name: write in file
   copy:
     content: "# Auth provider class (authenticates user/pass combination, needed if using the provided login screen)"
     dest: /etc/guacamole/guacamole.properties
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

 - name: write in file
   copy:
     content: "auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider"
     dest: /etc/guacamole/guacamole.properties
   when:
     - ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

 - name: shell
   shell: "sed -i '/^basic-user-mapping.*$/d' /etc/guacamole/guacamole.properties"

 - name: shell
   shell: "sed -i '/^mysql-.*$/d' /etc/guacamole/guacamole.properties"

 - name: shell
   shell: "sed -i '/^lib-directory:.*$/d' /etc/guacamole/guacamole.properties"

 - name: shell
   shell: "sed -i '/^noauth-config:.*$/d' /etc/guacamole/guacamole.properties"

# wite in file /etc/guacamole/guacamole.properties for all

 - name: write in file
   copy:
     content: "mysql-disallow-simultaneous-connections: false"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-disallow-duplicate-connections: false"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "lib-directory: /var/lib/guacamole/classpath\n"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-hostname: localhost"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-port: 3306"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-database: guacamole"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-username: guacamole"
     dest: /etc/guacamole/guacamole.properties

 - name: write in file
   copy:
     content: "mysql-password: {{ ROOT_PASSWORD }}"
     dest: /etc/guacamole/guacamole.properties

    # Setup Tomcat

 - name: shell
   shell: sed -i 's/Connector port="8080"/Connector port="8081"/' /etc/{{ V_TOMCAT_TEST_DEB }}/server.xml
   when:
     - ansible_distribution == "Debian"

 - name: shell
   shell: sed -i 's/Connector port="8080"/Connector port="8081"/' /etc/tomcat/server.xml
   when:
     - ansible_distribution == "CentOS"

 - name: shell
   shell: |
     xmlstarlet ed --inplace -s "Server[@port='8005']/Service[@name='Catalina']/Engine[@name='Catalina']/Host[@name='localhost']" -t elem -n "Valve className=\"org.apache.catalina.valves.RemoteAddrValve\" allow=\"{{ IP_ADDRESS }}\"" /etc/{{ V_TOMCAT_TEST_DEB }}/server.xml
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian"

 - name: shell
   shell: |
     xmlstarlet ed --inplace -s "Server[@port='8005']/Service[@name='Catalina']/Engine[@name='Catalina']/Host[@name='localhost']" -t elem -n "Valve className=\"org.apache.catalina.valves.RemoteAddrValve\" allow=\"{{ IP_ADDRESS }}\"" /etc/tomcat/server.xml
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "CentOS"

 - name: shell
   shell: |
     xmlstarlet ed --inplace -s "Server[@port='8005']/Service[@name='Catalina']/Engine[@name='Catalina']/Host[@name='localhost']" -t elem -n "Valve className=\"org.apache.catalina.valves.RemoteAddrValve\" allow=\"{{ PULSEMAIN_IP }}\"" /etc/{{ V_TOMCAT_TEST_DEB }}/server.xml
   when:
     - INSTALL_TYPE != "p"
     - ansible_distribution == "Debian"

 - name: shell
   shell: |
     xmlstarlet ed --inplace -s "Server[@port='8005']/Service[@name='Catalina']/Engine[@name='Catalina']/Host[@name='localhost']" -t elem -n "Valve className=\"org.apache.catalina.valves.RemoteAddrValve\" allow=\"{{ PULSEMAIN_IP }}\"" /etc/tomcat/server.xml
   when:
     - INSTALL_TYPE != "p"
     - ansible_distribution == "CentOS"

 - name: service tomcat restart
   service:
     name: '{{ V_TOMCAT_TEST_DEB }}'
     state: restarted
   when:
     - ansible_distribution == "Debian"

 - name: service tomcat restart
   service:
     name: 'tomcat'
     state: restarted
   when:
     - ansible_distribution == "CentOS"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/apache2/conf-available/guacamole.conf'
   when:
     - ansible_distribution == "Debian"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/httpd/conf.d/guacamole.conf'
   when:
     - ansible_distribution != "Debian"

 #    # Setup Apache FOR PULSE PRINCIPALE /!\
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: "<Location /guacamole/>"
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    SetEnvIf Referer \"^https?://{{ SERVER_FQDN }}/\" GUACAMOLE_ALLOWED'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Order Deny,Allow'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Deny from all'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Allow from env=GUACAMOLE_ALLOWED'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Get hostname f
 #   shell: hostname -f
 #   register: reshostf
 #
 # - name: set hostname f
 #   set_fact:
 #     HOSTNAME_F: "{{ reshostf.stdout }}"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '</Location>'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '<Location /guacamole/websocket-tunnel>'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    SetEnvIf Referer \"^https?://{{ SERVER_FQDN }}/\" GUACAMOLE_ALLOWED'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Order Deny,Allow'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Deny from all'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    Allow from env=GUACAMOLE_ALLOWED'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '    ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: '</Location>'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"
 #
 # - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
 #   copy:
 #     content: 'SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog'
 #     dest: '{{ GUACAMOLE_APACHE_PATH }}'
 #   when:
 #     - INSTALL_TYPE == "p"

#Debian

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: 'CustomLog  /var/log/apache2/guac.log common env=!dontlog'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: 'CustomLog  /var/log/httpd/guac.log common env=!dontlog'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution != "Debian"

 - name: a2enconf
   shell: 'a2enconf guacamole.conf'
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: apache2
     state: restarted
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: httpd
     state: restarted
   when:
     - ansible_distribution != "CentOS"
     - INSTALL_TYPE == "p"

#else INSTALL_TYPE != p
 - debug:
     msg: '{{ GUACAMOLE_APACHE_PATH }}'

 - debug:
     msg: '{{ SSH_COMMAND }}'

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '<Location /guacamole-{{ XMPP_DOMAIN }}/>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    SetEnvIf Referer \\\"^https?://{{ PULSEMAIN_FQDN }}/\\\" GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Order Deny,Allow'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Deny from all'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Allow from env=GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPass http://{{ SERVER_FQDN }}:8081/guacamole/ max=20 flushpackets=on'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverse http://{{ SERVER_FQDN }}:8081/guacamole/'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverseCookiePath /guacamole/ /guacamole-{{ XMPP_DOMAIN}}/'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '</Location>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '<Location /guacamole-{{ XMPP_DOMAIN }}/websocket-tunnel>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    SetEnvIf Referer \\\"^https?://{{ PULSEMAIN_FQDN }}/\\\" GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Order Deny,Allow'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Deny from all'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Allow from env=GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPass ws://{{ SERVER_FQDN }}:8081/guacamole/websocket-tunnel'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverse ws://{{ SERVER_FQDN }}:8081/guacamole/websocket-tunnel'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverseCookiePath /guacamole/ /guacamole-{{XMPP_DOMAIN }}/'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '</Location>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE != "p"

# if debian

 - name: restart systemdctl apache
   systemd:
     name: apache2
     state: restarted
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: restart systemdctl apache
   systemd:
     name: httpd
     state: restarted
   when:
     - ansible_distribution == "CentOS" or ansible_distribution == "Rhel"
