DBADMINUSER: root
DBADMINPASSWD: '{{ ROOT_PASSWORD }}'
GUACAMOLE_ROOT_PASSWORD: '' # GUACAMOLE_ROOT_PASSWORD is set by the role to be used by other roles
GUACDBPASSWD: '{{ ROOT_PASSWORD }}'
PULSEMAIN_IP: '' # PULSEMAIN_IP must be set on relays
INTERFACE: '{{ ansible_default_ipv4.interface }}'
IP_ADDRESS: "{{ vars['ansible_'~INTERFACE].ipv4.address }}"
