---

 - name: Get hostname
   shell: hostname -f
   register: result

 - name: set xmppDomain = 1
   set_fact:
     HOSTNAME_F: "{{ result.stdout }}"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/apache2/conf-available/guacamole.conf'
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/httpd/conf.d/guacamole.conf'
   when:
     - ansible_distribution != "Debian" or ansible_distribution != "Mageia"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: |
       CustomLog  /var/log/apache2/guac.log common env=!dontlog
       <Location /guacamole/>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on
           ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/
       </Location>
       <Location /guacamole/websocket-tunnel>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
           ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
       </Location>
       SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: |
       CustomLog  /var/log/httpd/guac.log common env=!dontlog
       <Location /guacamole/>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on
           ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/
       </Location>
       <Location /guacamole/websocket-tunnel>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
           ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
       </Location>
       SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: a2enconf
   shell: 'a2enconf guacamole.conf'
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: apache2
     state: restarted
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: httpd
     state: restarted
   when:
     - ansible_distribution != "CentOS"
     - INSTALL_TYPE == "p"
 #    # Setup Apache FOR PULSE PRINCIPALE /!\

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_packages {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_packages {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_bootmenus {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_bootmenus {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_baseremoteagent {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_baseremoteagent {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_downloads {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_downloads {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse
