---
####___________GUACAMOLE_____________
 - name: Get hostname
   shell: hostname -f
   register: result

 - name: set xmppDomain = 1
   set_fact:
     HOSTNAME_F: "{{ result.stdout }}"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/apache2/conf-available/guacamole.conf'
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/httpd/conf.d/guacamole.conf'
   when:
     - ansible_distribution != "Debian" or ansible_distribution != "Mageia"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: |
       CustomLog  /var/log/apache2/guac.log common env=!dontlog
       <Location /guacamole/>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on
           ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/
       </Location>
       <Location /guacamole/websocket-tunnel>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
           ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
       </Location>
       SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: |
       CustomLog  /var/log/httpd/guac.log common env=!dontlog
       <Location /guacamole/>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on
           ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/
       </Location>
       <Location /guacamole/websocket-tunnel>
           SetEnvIf Referer "^https?://{{ SERVER_FQDN }}/" GUACAMOLE_ALLOWED
           Order Deny,Allow
           Deny from all
           Allow from env=GUACAMOLE_ALLOWED
           ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
           ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel
       </Location>
       SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: a2enconf
   shell: 'a2enconf guacamole.conf'
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: apache2
     state: restarted
   when:
     - ansible_distribution == "CentOS"
     - INSTALL_TYPE == "p"

 - name:
   systemd:
     name: httpd
     state: restarted
   when:
     - ansible_distribution != "CentOS"
     - INSTALL_TYPE == "p"
 #    # Setup Apache FOR PULSE PRINCIPALE /!\

 ####___________SYNCTHING_____________

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_packages {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_packages {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_bootmenus {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_bootmenus {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: shell
   shell: stman folder unshare pulsemaster_baseremoteagent {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_baseremoteagent {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 # - name: shell
 #   shell: stman folder unshare pulsemaster_downloads {{ LOCAL_DEVICE_ID }}
 #   when:
 #     - SHARE_ADDED == ''
 #     - XMPP_DOMAIN != pulse

 - name: shell
   shell: stman folder share pulsemaster_downloads {{ LOCAL_DEVICE_ID }}
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != pulse

 - pause:
     seconds: 20

 - name: set SHARE_ADDED
   set_fact:
     SHARE_ADDED: $(xmlstarlet sel -t -c "configuration/folder[@id='pulsemaster_packages']/device[@id='{{ LOCAL_DEVICE_ID }}']" /var/lib/syncthing/.config/syncthing/config.xml |wc -c)
   when:
     - SHARE_ADDED == ''
     - XMPP_DOMAIN != 'pulse'

####Syncthing_depl write

 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/apache2/conf-available/syncthing.conf'
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"

 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/httpd/conf.d/syncthing.conf'
   when:
     - ansible_distribution != "Debian" or ansible_distribution != "Mageia"


 - name: write in {{ SYNCTHING_APACHE_PATH }}
   lineinfile:
     line: "ProxyPass /syncthing-depl-{{ XMPP_DOMAIN }}/ http://{{ XMPP_DOMAIN }}/syncthing-depl/"
     dest: '{{ SYNCTHING_APACHE_PATH }}'

 - name: write in {{ SYNCTHING_APACHE_PATH }}
   lineinfile:
     line: "<Location /syncthing-depl-{{ XMPP_DOMAIN }}/>"
     dest: '{{ SYNCTHING_APACHE_PATH }}'

 - name: write in {{ SYNCTHING_APACHE_PATH }}
   lineinfile:
     line: "    ProxyPassReverse http://{{ XMPP_DOMAIN }}/syncthing-depl/"
     dest: '{{ SYNCTHING_APACHE_PATH }}'

 - name: write in {{ SYNCTHING_APACHE_PATH }}
   lineinfile:
     line: "    Require all granted"
     dest: '{{ SYNCTHING_APACHE_PATH }}'

 - name: write in {{ SYNCTHING_APACHE_PATH }}
   lineinfile:
     line: "</Location>"
     dest: '{{ SYNCTHING_APACHE_PATH }}'

#reload apache2.service

 - name: set SSH_COMMAND
   systemd:
     name: apache2
     state: reload
   when:
     - ansible_distribution == "Debian" or ansible_distribution == 'Mageia'

 - name: set SSH_COMMAND
   systemd:
     name: httpd
     state: reload
   when:
     - ansible_distribution != "Debian" or ansible_distribution != 'Mageia'

 - name: shell
   shell: if [ \"\$(grep -cx \"{{ IP_REMOTE_SERVER }} {{ XMPP_DOMAIN }}\" /etc/hosts)\" -eq 0 ]; then echo \"{{ IP_REMOTE_SERVER }} {{ XMPP_DOMAIN }}\" >> /etc/hosts; fi
