---

 - name: Get hostname
   shell: hostname -s
   register: result

 - name: set xmppDomain = 1
   set_fact:
     XMPP_DOMAIN: "{{ result.stdout }}"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/apache2/conf-available/guacamole.conf'
   when:
     - ansible_distribution == "Debian"

 - name: set GUACAMOLE_ROOT_PASSWORD
   set_fact:
     GUACAMOLE_APACHE_PATH: '/etc/httpd/conf.d/guacamole.conf'
   when:
     - ansible_distribution != "Debian"

 #    # Setup Apache FOR PULSE PRINCIPALE /!\

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: "<Location /guacamole/>"
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    SetEnvIf Referer \"^https?://{{ SERVER_FQDN }}/\" GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Order Deny,Allow'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Deny from all'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Allow from env=GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Get hostname f
   shell: hostname -f
   register: reshostf

 - name: set hostname f
   set_fact:
     HOSTNAME_F: "{{ reshostf.stdout }}"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPass http://{{ HOSTNAME_F }}:8081/guacamole/ max=20 flushpackets=on'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverse http://{{ HOSTNAME_F }}:8081/guacamole/'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '</Location>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '<Location /guacamole/websocket-tunnel>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    SetEnvIf Referer \"^https?://{{ SERVER_FQDN }}/\" GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Order Deny,Allow'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Deny from all'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    Allow from env=GUACAMOLE_ALLOWED'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPass ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '    ProxyPassReverse ws://{{ HOSTNAME_F }}:8081/guacamole/websocket-tunnel'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: '</Location>'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"

 - name: Setup Apache write in {{ GUACAMOLE_APACHE_PATH }}
   copy:
     content: 'SetEnvIf Request_URI \"^/guacamole/tunnel\" dontlog'
     dest: '{{ GUACAMOLE_APACHE_PATH }}'
   when:
     - INSTALL_TYPE == "p"
