IMAGING_UUID: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') | to_uuid }}"
PUBLIC_IP: ''
PULSEMAIN_IP: '' # PULSEMAIN_IP must be set if package server is installed on a separate server
