---

 - name: config mysql_access
   shell: "/bin/rm -f /root/.my.cnf"

 - name: Touch file chmode600
   file:
     path: /root/.my.cnf
     state: touch
     mode: '600'

 - name: copy file
   lineinfile:
     line: "[mysql]\nuser={{ DBADMINUSER }}\npassword={{ DBADMINPASSWD }}"
     dest: /root/.my.cnf

 - name: copy file
   lineinfile:
     line: "\n[mysqladmin]\nuser={{ DBADMINUSER }}\npassword={{ DBADMINPASSWD }}"
     dest: /root/.my.cnf

 - name: copy file
   lineinfile:
     line: "\n[mysqlcheck]\nuser={{ DBADMINUSER }}\npassword={{ DBADMINPASSWD }}"
     dest: /root/.my.cnf

 - name: copy file
   lineinfile:
     line: "\n[mysqldump]\nuser={{ DBADMINUSER }}\npassword={{ DBADMINPASSWD }}"
     dest: /root/.my.cnf

 - name: restart mariadb
   service:
     name: mysql
     state: restarted
   when:
     - ansible_distribution != "CentOS"

 - name: restart mariadb
   service:
     name: mariadb
     state: restarted
   when:
     - ansible_distribution == "CentOS"

 - name: chkconfig mariadb
   service:
     name: mysql
     enabled: yes
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"
