- name: Pulse Main
  gather_facts: true
  hosts: mmc
  remote_user: root
  serial: 1
  roles:
    - base
    - security
    - pki
    - php
    - ldap
    - mariadb
    - ejabberd
    - syncthing_discosrv
    - syncthing_relay
    - syncthing
    - urbackup
    - ssh
    - { role: glpi, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'glpi') }
    - { role: itsm-ng, when: (ITSM_DBHOST == 'localhost' and ITSM_TYPE == 'itsm-ng') }
    - guacamole
    - grafana
    - nfs
    - mmc
    - { role: substitute_agent, SUBS_LONG_TYPE: 'subscription' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'assessor' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'inventory' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'registration' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'logger' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'deployment' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'monitoring' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'reconfigurator' }
    - { role: substitute_agent, SUBS_LONG_TYPE: 'updates' }
    - relay_agent
    - pulse_file_browser
    - pulse_packageserver
    - pxe_registration
    - pulse_imaging
    - medulla_osupdates
    - pulse_main

  # tasks:
  #   - name: SUBSTITUTE_AGENT - Find out name of substitute
  #     mysql_query:
  #       login_host: localhost
  #       login_port: 3306
  #       login_user: root
  #       login_password: siveo
  #       login_db: 'xmppmaster'
  #       query:
  #        - SELECT COUNT( DISTINCT jidsubtitute ) FROM substituteconf  WHERE type = %(type)s")
  #       named_args:
  #         type: 'registration'
  #     register: res_query

  #   - name: Result
  #     debug:
  #       var: res_query
