- name: Pulse Relay
  gather_facts: true
  hosts: ars
  remote_user: root
  serial: 1
  roles:
    - base
    - mariadb
    - ejabberd
    - syncthing
    - ssh
    - guacamole
    - nfs
    - relay_agent
    - pulse_packageserver
    - pulse_imaging
    - pulse_relay
    - security
