---

 - name: Restart apache
   systemd:
     name: httpd
     state: restarted
     daemon_reload: yes
   when:
     - ansible_distribution == 'CentOS'

 - name: Reload apache
   systemd:
     name: httpd
     state: reloaded
     daemon_reload: yes
   when:
     - ansible_distribution == 'CentOS'

 - name: Restart php-fpm
   systemd:
     name: php-fpm
     state: restarted
   when:
     - ansible_distribution == 'CentOS'

 - name: Restart mariadb
   systemd:
     name: mariadb
     state: restarted

 - name: Restart relay
   systemd:
     name: pulse-xmpp-agent-relay
     state: restarted
