---

 - name: Get hostname
   shell: hostname -s
   register: result

 - name: set xmppDomain = 1
   set_fact:
     XMPP_DOMAIN: "{{ result.stdout }}"

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - shell: '{{ LOCAL_DEVICE_ID }}'
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: '{{ deviceid.stdout }}'

 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/apache2/conf-available/syncthing.conf'
   when:
     - ansible_distribution == "Debian"

 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/httpd/conf.d/syncthing.conf'
   when:
     - ansible_distribution != "Debian"

# Configure Apache for syncthing

 - name: Setup syncthing write in {{ SYNCTHING_APACHE_PATH }}
   copy:
     content: |
       ProxyPass /syncthing/ http://localhost:8384/
       <Location /syncthing/>
           ProxyPassReverse http://localhost:8384/
           Require all granted
       </Location>
     dest: '{{ SYNCTHING_APACHE_PATH }}'

 - name: shell
   command: 'a2enconf syncthing'
   when:
     - ansible_distribution == "Debian"

 - name: reload apache2
   systemd:
     name: apache2
     state: reloaded
   when:
     - ansible_distribution == "Debian"

 - name: reload apache2
   systemd:
     name: httpd
     state: reloaded
   when:
     - ansible_distribution != "Debian"

## IF XMPP_DOMAIN != PULSE

#Verifie
 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/apache2/conf-available/syncthing.conf'
   when:
     - ansible_distribution == "Debian"

 - name: set SYNCTHING_APACHE_PATH
   set_fact:
     SYNCTHING_APACHE_PATH: '/etc/httpd/conf.d/syncthing.conf'
   when:
     - ansible_distribution != "Debian"

 - name: Ansible check file exists example.
   stat:
     path: /etc/apache2/conf-available
   register: file_details
   delegate_to: pulse

 - name: Setup syncthing write in {{ SYNCTHING_APACHE_PATH }}
   copy:
     content: |
       ProxyPass /syncthing-{{ XMPP_DOMAIN }}/ http://{{ XMPP_DOMAIN }}/syncthing/
       <Location /syncthing-{{ XMPP_DOMAIN }}/>
           ProxyPassReverse http://{{ XMPP_DOMAIN }}/syncthing/
           Require all granted
       </Location>
     dest: '{{ SYNCTHING_APACHE_PATH }}'
   delegate_to: pulse
   when:
     - file_details.stat.exists

## for Rhel

 - name: Ansible check file exists example.
   stat:
     path: /etc/httpd/conf.d
   register: file_details
   delegate_to: pulse

 - name: Setup syncthing write in {{ SYNCTHING_APACHE_PATH }}
   copy:
     content: |
       ProxyPass /syncthing-{{ XMPP_DOMAIN }}/ http://{{ XMPP_DOMAIN }}/syncthing/
       <Location /syncthing-{{ XMPP_DOMAIN }}/>
           ProxyPassReverse http://{{ XMPP_DOMAIN }}/syncthing/
           Require all granted
       </Location>
     dest: '{{ SYNCTHING_APACHE_PATH }}'
   delegate_to: pulse
   when:
     - file_details.stat.exists

 - name: Check if Service Exists
   stat: path=/etc/init.d/apache2
   register: service_status
   delegate_to: pulse

 - name: reload systemd
   systemd:
     name: apache2
     state: reloaded
   delegate_to: pulse
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"
     - service_status.stat.exists

 - name: Check if Service Exists
   stat: path=/etc/init.d/httpd
   register: service_status
   delegate_to: pulse

 - name: reload systemd
   systemd:
     name: httpd
     state: reloaded
   delegate_to: pulse
   when:
     - ansible_distribution == "CentOS" or ansible_distribution == "Rhel"
     - service_status.stat.exists

## end delegate to

 - name: start syncthing
   systemd:
     name: syncthing.discosrv
     state: started
   when:
     - XMPP_DOMAIN == 'pulse'

# Stop syncthing service

 - name: stop syncthing
   systemd:
     name: syncthing@syncthing
     state: stopped

# Use the local discovery server

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -u "configuration/options/globalAnnounceServer" -v "https://localhost:8443/?id={{ LOCAL_DEVICE_ID }}" /var/lib/syncthing/.config/syncthing/config.xml
   when:
     - XMPP_DOMAIN == 'pulse'

# Find pulsemain device id

# TO DELEGATE
 - name: set SSH_COMMAND
   set_fact:
     SSH_COMMAND: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id
   delegate_to: pulse
   when:
     - XMPP_DOMAIN != "pulse"

 - name: set PULSEMAIN_DEVICE_ID
   set_fact:
     PULSEMAIN_DEVICE_ID: 'ssh {{ PULSEMAIN_IP }} {{ SSH_COMMAND }}'
   delegate_to: pulse
   when:
     - XMPP_DOMAIN != "pulse"

 - name: recup id pulsemain and sshcommand
   shell: '{{ PULSEMAIN_DEVICE_ID }}'
   register: resid
   delegate_to: pulse
   when:
     - XMPP_DOMAIN != "pulse"

 - name: set PULSEMAIN_DEVICE_ID
   set_fact:
     PULSEMAIN_DEVICE_ID: '{{ resid.stdout }}'
   delegate_to: pulse
   when:
     - XMPP_DOMAIN != "pulse"

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -u "configuration/options/globalAnnounceServer" -v "https://{{ PULSEMAIN_FQDN }}:8443/?id={{ PULSEMAIN_DEVICE_ID }}" /var/lib/syncthing/.config/syncthing/config.xml
   delegate_to: pulse
   when:
     - XMPP_DOMAIN != 'pulse'
#END DELEGATE TO


    # Disable use of syncthing relays and local announce

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -u "configuration/options/relaysEnabled" -v "false" /var/lib/syncthing/.config/syncthing/config.xml

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -u "configuration/options/localAnnounceEnabled" -v "false" /var/lib/syncthing/.config/syncthing/config.xml

# Setup a username and password for accessing syncthing

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -s "configuration/gui" -t elem -n user -v root /var/lib/syncthing/.config/syncthing/config.xml

 - name: set ENCRYPTED_PASS
   set_fact:
     ENCRYPTED_PASS: $(htpasswd -bnBC 10 "" {{ ROOT_PASSWORD }} | tr -d ':\n' | sed 's/$2y/$2a/')

 - name: xmlstarlet
   shell: xmlstarlet ed --inplace -s "configuration/gui" -t elem -n password -v {{ ENCRYPTED_PASS }} /var/lib/syncthing/.config/syncthing/config.xml

# Restart syncthing service

 - name: restarted syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: restarted

 - pause:
     seconds: 5

    # Configure syncthingmanager

 - name: set API_KEY
   set_fact:
     API_KEY: '$(xmlstarlet sel -t -v "configuration/gui/apikey" /var/lib/syncthing/.config/syncthing/config.xml)'

 - name: stman
   shell: 'stman configure -k {{ API_KEY }}'

# Change the name to use the same as the XMPP domain

 - name: stman
   shell: 'stman device edit -n {{ XMPP_DOMAIN }} {{ LOCAL_DEVICE_ID }}'

    # Add device to pool if relay server
    # Add device to pool on pulsemain

 - name: set SSH_COMMAND
   set_fact:
     SSH_COMMAND: 'stman device add --name {{ XMPP_DOMAIN }} --address tcp://{{ IP_ADDRESS }}:22000 {{ LOCAL_DEVICE_ID }}'
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: ssh
   shell: ssh {{ PULSEMAIN_IP }} stman device add --name {{ XMPP_DOMAIN }} --address tcp://{{ IP_ADDRESS }}:22000 {{ LOCAL_DEVICE_ID }}
   when:
     - XMPP_DOMAIN != 'pulse'

# Find pulsemain device id

 - name: set SSH_COMMAND
   set_fact:
     SSH_COMMAND: 'syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id'
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: set PULSEMAIN_DEVICE_ID
   set_fact:
     PULSEMAIN_DEVICE_ID: '$(ssh {{ PULSEMAIN_IP }} {{ SSH_COMMAND }})'
   when:
     - XMPP_DOMAIN != 'pulse'

# Add pulsemain to local pool

 - name: stman
   shell: stman device add --name pulse --address tcp://{{ PULSEMAIN_IP }}:22000 --introducer {{ PULSEMAIN_DEVICE_ID }}
   when:
     - XMPP_DOMAIN != 'pulse'

 # Auto-accept shares coming from pulsemain

 - name: stman
   shell: xmlstarlet ed --inplace -u "configuration/device[@id='{{ PULSEMAIN_DEVICE_ID }}']/autoAcceptFolders" -v true /var/lib/syncthing/.config/syncthing/config.xml
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: restart syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: restarted
   when:
     - XMPP_DOMAIN != 'pulse'

 - pause:
     seconds: 10
   when:
     - XMPP_DOMAIN != 'pulse'

    # Delete the default share

 - name: stman
   shell: 'stman folder remove "Default Folder"'
