---

 - name: Get hostname
   shell: hostname -s
   register: result

 - name: set xmppDomain = 1
   set_fact:
     XMPP_DOMAIN: "{{ result.stdout }}"

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: syncthing -home=/var/lib/syncthing/.config/syncthing/ -device-id

 - name: shell
   shell: ' {{ LOCAL_DEVICE_ID }} '
   register: deviceid

 - name: set LOCAL_DEVICE_ID
   set_fact:
     LOCAL_DEVICE_ID: "{{ deviceid.stdout }}"

 - name: delete file if present
   file:
     path: /var/lib/syncthing/downloads
     state: absent

 - name: create file
   file:
     path: /var/lib/pulse2/clients
     state: directory
     mode: '0755'

 - name: write in .stignore
   copy:
     content: "config\ngenerate-*\nreversessh\n.generation_options"
     dest: /var/lib/pulse2/clients/.stignore
   when:
     - XMPP_DOMAIN == 'pulse'

 - name: write in .stignore
   copy:
     content: "reversessh"
     dest: /var/lib/pulse2/clients/.stignore
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: create file
   file:
     path: /var/lib/pulse2/clients/.stfolder
     state: directory
     mode: '0755'

 - name: chown
   shell: 'chown syncthing: /var/lib/pulse2/clients'

 # - name: chown
 #   shell: 'chown -R syncthing: /var/lib/pulse2/clients/{lin,win,mac,pulse-*.tar.gz,style.css,.st*}'

 - name: chown
   shell: 'chown -R syncthing: /var/lib/pulse2/clients/.st*'

 - name: shell
   shell: setfacl -Rdm g:syncthing:rwx /var/lib/pulse2/clients/.st*

 - name: shell
   shell: setfacl -Rm g:syncthing:rwx /var/lib/pulse2/clients/.st*

## Ne sert à rien pour le moment tant car ansible ne fait que les ars, sera utile une fois que ansible configurera pp
 - name: stman
   shell: stman folder add --label downloads --foldertype readonly /var/lib/pulse2/clients/ pulsemaster_downloads
   when:
     - XMPP_DOMAIN == 'pulse'

 - name: restarted syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: stopped
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: Check if d folder is empty before proceeding
   find:
     paths: '/var/lib/syncthing/downloads/'
   register: filesFound

 - name: Move foo to bar
   command: mv /var/lib/syncthing/downloads/.st*  /var/lib/pulse2/clients/
   when:
     - XMPP_DOMAIN != 'pulse'
     - filesFound.matched > 0

 - name: delete file if present
   file:
     path: /var/lib/syncthing/downloads
     state: absent
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: shell
   shell: xmlstarlet ed --inplace -u "configuration/folder[@id="pulsemaster_downloads"]/@path" -v "/var/lib/pulse2/clients" /var/lib/syncthing/.config/syncthing/config.xml
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: restarted syncthing@syncthing
   systemd:
     name: syncthing@syncthing
     state: restarted
   when:
     - XMPP_DOMAIN != 'pulse'

 - pause:
     seconds: 5
   when:
     - XMPP_DOMAIN != 'pulse'

 - name: a2enconf pulse
   shell: a2enconf pulse
   when:
     - ansible_distribution == "Debian" or ansible_distribution == "Mageia"
