---

 - name: set event_scheduler on
   shell: 'echo "SET GLOBAL event_scheduler = ON" | mysql -h {{ DBHOST }} -P {{ DBPORT }} -u{{ DBADMINUSER }} -p{{ DBADMINPASSWD }}'
   when:
     - XMPP_DOMAIN == 'pulse'

 - name: creat 99-pulse.cnf
   file:
     state: touch
     path: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "[mariadb]"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "table_open_cache = 2000"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "query_cache_limit = 0"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "query_cache_size = 0"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "tmp_table_size = 2G"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "innodb_buffer_pool_size = 2G"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "key_buffer_size = 2G"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "max_heap_table_size = 2G"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "open_files_limit = 102400"
     dest: /etc/mysql/mariadb.conf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Debian"
     - XMPP_DOMAIN == 'pulse'

 - name: Create pulse-99.cnf
   file:
     path: /etc/my.cnf.d/99-pulse.cnf
     state: touch
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "[mariadb]"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "table_open_cache = 2000"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "query_cache_limit = 0"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "query_cache_size = 0"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "tmp_table_size = 2G"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "innodb_buffer_pool_size = 2G"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "key_buffer_size = 2G"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "max_heap_table_size = 2G"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'

 - name: copy data
   lineinfile:
     line: "open_files_limit = 102400"
     dest: /etc/my.cnf.d/99-pulse.cnf
   when:
     - ansible_distribution == "Mageia" or ansible_distribution == "Rhel" or ansible_distribution == "CentOS"
     - XMPP_DOMAIN == 'pulse'
